packages:
  - packages/*

catalog:
  vitest: ^3.2.4
  "@vitest/ui": ^3.2.4
  ts-pattern: ^5.8.0
  es-toolkit: ^1.39.3
  "@types/node": ^22.18.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sentry/cli"
  - esbuild
  - sharp

engineStrict: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@portone/ai-chatbot-loader"
