packages:
  - packages/*

catalog:
  '@types/node': ^24.10.13
  '@vitest/ui': ^3.2.4
  es-toolkit: ^1.39.3
  ts-pattern: ^5.9.0
  vitest: ^4.0.18

engineStrict: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@portone/ai-chatbot-loader'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - esbuild
  - sharp

overrides:
  '@babel/generator@>=7.29.1 <7.30.0': ^7.29.1
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  mdast-util-from-markdown@0.8.5: ^2.0.2
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  vite: ^8.0.0-beta.15

patchedDependencies:
  eslint-plugin-mdx: patches/eslint-plugin-mdx.patch
  eslint-plugin-prettier: patches/eslint-plugin-prettier.patch
  remark-lint-table-cell-padding: patches/remark-lint-table-cell-padding.patch
  vite-imagetools: patches/vite-imagetools.patch
