packages:
  - packages/*

catalog:
  vitest: ^3.2.2
  ts-pattern: ^5.7.1
  es-toolkit: ^1.39.3
  '@types/node': ^22.15.30

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - esbuild
  - sharp
