#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

# NODE_OPTIONS is used to pass ts-node loader to entire node process
export NODE_OPTIONS="--loader $basedir/node_modules/ts-node/esm.mjs"
export TS_NODE_PROJECT="$basedir/tsconfig.json"

exec node "$@"
