name: Lint

on: push

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    runs-on: ubuntu-latest
    name: Lint code and MDX files
    permissions:
      # Required to checkout the repository
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm update-schema
      - run: pnpm gen-collections
      - run: pnpm check
