name: Server SDK

on:
  push:
    branches: [main]
    paths:
      - "src/schema/v2.openapi.json"
  workflow_dispatch: {}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync OpenAPI to Server SDK
    environment: sdk-sync
    permissions:
      # Required to checkout the repository
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: portone-io/server-sdk
          path: sdk
          ref: main
          token: ${{ secrets.SDK_REPO_TOKEN }}
          persist-credentials: false

      - name: Create new branch
        run: git checkout -b chore/openapi
        working-directory: sdk

      - name: Copy OpenAPI schema
        run: cp src/schema/v2.openapi.json sdk/codegen/openapi.json

      - name: Install Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2
        with:
          deno-version: v2.x

      - name: Generate SDK code
        run: |
          deno run -A main.ts js && deno run -A main.ts py && deno run -A main.ts jvm
        working-directory: sdk/codegen

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: "sdk/javascript/pnpm-lock.yaml"

      - name: Add empty changeset
        run: npx @changesets/cli add --empty
        working-directory: sdk/javascript

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
        with:
          enable-cache: true
          working-directory: "sdk/python"

      - name: Install dependencies
        run: uv sync --dev
        working-directory: sdk/python

      - name: Format Python code
        run: uv run ruff format
        working-directory: sdk/python

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: update OpenAPI schema"
          git remote set-url origin "https://x-access-token:${SDK_REPO_TOKEN}@github.com/portone-io/server-sdk.git"
          git push -f origin chore/openapi
        working-directory: sdk
        env:
          SDK_REPO_TOKEN: ${{ secrets.SDK_REPO_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create \
            --repo portone-io/server-sdk \
            --title "chore: update OpenAPI schema" \
            --body "OpenAPI 스키마가 업데이트되어 자동으로 생성된 PR입니다." \
            --base main \
            --head chore/openapi
        env:
          GH_TOKEN: ${{ secrets.SDK_REPO_TOKEN }}
